### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by Iaotle** [Kouzukii/ffxiv-priceinsight#1]
Hi, cool mod, but noticed that you still don't have it up on the repo, as well as having duplicates of mods already in the default one. 
Could you please add a working repo?

**Comment by Kouzukii** [comment]
That's not up to me, the merge request on dalamud plugins has been up for 3 weeks :D

https://github.com/goatcorp/DalamudPlugins/pull/1004

You can download the plugin zip and install it manually of course. And while this does essentially the same as PriceCheck it's a lot more convenient.

**Comment by Iaotle** [comment]
I think the idea is that you can set up your own repo without waiting, which you already have done, except you didn't delete all of the duplicate entries and didn't add your own mod. Should be more or less easy to fix though, if you feel like it.

**Comment by Kouzukii** [comment]
Oh I didn't see they added third party repositories, I'll give that a shot

**Comment by Iaotle** [comment]
Can't find anything even after adding repo. Are you sure it works?

**Comment by Iaotle** [comment]
Dalamud has been updated, so I think your plugin might be outdated. I've added your repo:
![image](https://user-images.githubusercontent.com/43072246/136677429-b50af951-006d-45bb-acda-1f1f7dc770b3.png)
and still no mod:
![image](https://user-images.githubusercontent.com/43072246/136677435-9f706487-2551-4bb4-9ab3-641560fc69bc.png)

**Comment by Iaotle** [comment]
Oop, now it works, cheers.
