### ISSUE TITLE
Unmarketable items still have info

### ISSUE THREAD

**Issue by filliph** [Kouzukii/ffxiv-priceinsight#11]
![image](https://user-images.githubusercontent.com/9424286/187497454-65eb665c-d1ed-4abd-b4a5-4942a2327f3b.png)

![image](https://user-images.githubusercontent.com/9424286/187497528-e48a0e56-e1e0-4064-8457-dccd095bb3f5.png)

**Comment by Kouzukii** [comment]
Yes key items have the same id as certain HQ items, I'll make sure to exclude them in the next update.

**Comment by filliph** [comment]
This is not fixed.

![image](https://user-images.githubusercontent.com/9424286/188314733-e00f6062-eea5-42ad-a3a6-298130e717a5.png)

![image](https://user-images.githubusercontent.com/9424286/188314744-b487a6dd-7b46-4d4d-a86e-389c0a504d1b.png)
