### ISSUE TITLE
Home World of first Character you log in for the day

### ISSUE THREAD

**Issue by drejjmit** [Kouzukii/ffxiv-priceinsight#13]
Instead of showing home world of current character it shows home world of the first character you logged in when you launched the client. Home world does not change when you log in a character on another world.

Here it shows ``Home (Phantom)`` even tho this characters home world is Sagittarius
![image](https://user-images.githubusercontent.com/15526476/188274981-aa0a4943-0463-46c1-a102-1c01cb125b70.png)

**Comment by Kouzukii** [comment]
I hadn't considered that, I cache home world information when first logging in, but it should be cleared when changing characters
