### ISSUE TITLE
Tooltips sliding down when set to fixed

### ISSUE THREAD

**Issue by Hiroa** [Kouzukii/ffxiv-priceinsight#14]
On the player option, when the tooltip is set fixed, it's position is sliding down (an up) each time I hover an item.  
I need to move it back with the ATH menu.  
I still have the issue when I disable "Simple Tweaks" and "Wich Patch Was That?".

I made a video in case my explanation was not clear.
https://www.youtube.com/watch?v=Pk_3aNYAcHE

**Comment by Kouzukii** [comment]
I see, I forgot about the fixed tooltip location setting. I'll have a look at that
