### ISSUE TITLE
[BUG] Price display = instead of , or empty space for long numbers on french client

### ISSUE THREAD

**Issue by Kery0x** [Kouzukii/ffxiv-priceinsight#19]
Hello. 
Problem with french client.
The price display is bugged for numbers with more than 3 digits (ie 1 000, 10 000, etc). It shows an equal symbol instead of a comma or an empty space.

![image](https://user-images.githubusercontent.com/121441173/209553804-4e9b2c42-1f94-4247-906e-3ac73f43a6d3.png)

**Comment by Necr0fantasia** [comment]
I believe it's a french only related issue, I found a way around by changing the digit grouping symbol like this :

![image](https://user-images.githubusercontent.com/27381879/210923133-636ef405-31ea-4a72-a26b-d6ce5873126a.png)
