### ISSUE TITLE
Prices aren't being displayed.

### ISSUE THREAD

**Issue by pacomesoual** [Kouzukii/ffxiv-priceinsight#20]
Most of the time the price indicator in the item's description shows up as "Marketboard info is being obtained" but it never does.
And sometimes it straight up doesn't show anything.

It may be a problem with universalis themselves because another Plugin I use "personal market board" ALSO doesn't fetch prices and current sales correctly and displays nothing instead.

Edit : I haven't been able to see Universalis prices in games through your plugin or any other for about a month now.

**Comment by AutyCandy** [comment]
Have also been having this issue for a few days but only sporadically.  Sometime it still works as normal, and sometimes it will execute exactly the above issue (perpetual "Marketboard info is being obtained") on *some* items but not others.
Seems worse during high traffic hours, but that's just anecdotal, I could be imagining that.

**Comment by xxBeethoven** [comment]
Same

**Comment by Kouzukii** [comment]
Prices are fetched from Universalis.app which can be unresponsive sometimes.
I've released a new version that will now display an error message if fetching the price failed.
You can also always press Alt to retry fetching the price or check the /xllog error message and send that to me.

**Comment by AutyCandy** [comment]
Oh thanks, tbh an error message just to make it clear that has happened will be great :)
