### ISSUE TITLE
Invalid status code InternalServerError

### ISSUE THREAD

**Issue by Clawthorn** [Kouzukii/ffxiv-priceinsight#24]
I know this is probably an issue on Universalis side, but I figured I'd raise an issue anyway since it might be nice to know about, and it's something I've never seen happening until today. Plus it might be good to handle this supposedly invalid status code in case it happens again.

Game tooltips are showing the following:
![image](https://user-images.githubusercontent.com/20911914/232056221-cc922e98-482c-4464-84a0-033256bc3872.png)

Pressing ALT in this instance fixes the issue for that particular item.
So it might be related to the option of prefetching the prices for items in inventory.

My settings are:
![image](https://user-images.githubusercontent.com/20911914/232056639-904031f9-8481-4433-b354-7f14434c3250.png)

And the exception in the log:
```
15:13:19.848 | ERR [PriceInsight] Failed to retrieve data from Universalis for itemIds [{ItemID List truncated for privacy}], scope "{Server Name truncated for privacy}".
System.Net.Http.HttpRequestException: Invalid status code InternalServerError
   at PriceInsight.UniversalisClient.GetMarketBoardDataList(String scope, UInt32 homeWorldId, List`1 itemId) in /work/repo/UniversalisClient.cs:line 63
```

**(ID list and server removed because I don't know if this information can be linked to me by SE and counts as an admission to breaking the ToS, but if I'm just being silly and you need that information, feel free to let me know)**

**Comment by KairaRegina** [comment]
Having the same issue, started recently.
