### ISSUE TITLE
[Bug] Text is spacing weirdly in tooltips 6.5

### ISSUE THREAD

**Issue by Felys1998** [Kouzukii/ffxiv-priceinsight#30]
Looks like text isnt rendering correctly in the tooltip since the patch.

![image](https://github.com/Kouzukii/ffxiv-priceinsight/assets/2600400/da0ff3a9-7bcc-481f-93f3-552177bebad1)

**Comment by drejjmit** [comment]
You just need a wider monitor
![image](https://github.com/Kouzukii/ffxiv-priceinsight/assets/15526476/22fcf2ff-f666-434b-ae74-1b3c3ebe5cff)

**Comment by Kouzukii** [comment]
Some of the changes from 6.5 now randomize the character spacing, in my tests it just so happened to randomize to the normal value 0 😆 
Fix should be live soon
