### ISSUE TITLE
Timezone calculation issue?

### ISSUE THREAD

**Issue by truecrisis** [Kouzukii/ffxiv-priceinsight#33]
When I hover on an item, it will say something like `300g (15h ago)` but in fact the price was just updated, so I'm lead to believe that the 15h calculation is just a bug. I'm constantly needing to do mental math to guess the actual freshness of the price.

Is this a known issue or a limitation? If not, I can try to help investigate if needed.

**Comment by Kouzukii** [comment]
I've had a look and indeed the time of the listing does not match the "last upload time" for that world on universalis. 
This number is however already reported incorrectly by the universalis API. 
I'll have a chat with karashiiro to see where the issue could be.

**Comment by Kouzukii** [comment]
e.g. https://universalis.app/api/v2/Spriggan/29431 (Neo-Ishgardian Bottoms of Maiming)
```json
{
  "itemID": 29431,
  "worldID": 85,
  "lastUploadTime": 1703799966102,
  "listings": [
    {
      "lastReviewTime": 1703747697,
      "pricePerUnit": 2999,
      "quantity": 1,
      "stainID": 0,
      "creatorName": "",
      ...
```
`"lastUploadTime": 1703799966102` = Thursday, December 28, 2023 9:46:06.102 PM GMT
`"lastReviewTime": 1703747697` = Thursday, December 28, 2023 7:14:57 AM GMT

**Comment by Kouzukii** [comment]
Alright looks like this is a misunderstanding on my part "lastReviewTime" refers to the time the item was posted (wouldn't something like "timeOfListing" be more descriptive?)
Well anyways, I'll be correcting the displayed timestamps to use the correct worldUploadTimes in the next update.

**Comment by truecrisis** [comment]
Thank you for looking into it!
I didn't realize you had two dates to work with. I was assuming that the `15h ago` was in reference to the time shown on Universalis:

<img width="309" alt="image" src="https://github.com/Kouzukii/ffxiv-priceinsight/assets/19563239/a5385d94-0dc9-4c26-9c64-9b80b724a04d">

I'm not sure what the "ReviewTime" vs "UploadTime" difference is, but I would expect the timestamp to reflect the last time the data was updated, like the picture above, same as the timestamp that Universalis provides.
