### ISSUE TITLE
Unable to Get Prices: Invalid Status code 520

### ISSUE THREAD

**Issue by Strider1321** [Kouzukii/ffxiv-priceinsight#40]
Hello!

The program was working fine after the update for a while but it hasn't been working for a week. After checking the log these are some of the errors I'm getting when trying to check a generic item. I have tried refreshing the plugin and removing and redownloading it.

```
19:10:48.054 | ERR | [PriceInsight] Failed to retrieve data from Universalis for itemId 27838, scope "Aether".
	System.Net.Http.HttpRequestException: Invalid status code Forbidden
	   at PriceInsight.UniversalisClient.GetMarketBoardData(String scope, UInt32 homeWorldId, UInt64 itemId) in /work/repo/UniversalisClient.cs:line 54
```

Here is the other error I'm getting
```
19:14:40.869 | ERR | [PriceInsight] Failed to retrieve data from Universalis for itemId 43991, scope "Aether".
	System.Net.Http.HttpRequestException: Invalid status code 520
	   at PriceInsight.UniversalisClient.GetMarketBoardData(String scope, UInt32 homeWorldId, UInt64 itemId) in /work/repo/UniversalisClient.cs:line 54
```

Any help is appreciated!

**Comment by hullmat998** [comment]
I'm also having this same issue. The /xllog is completely full of nothing but errors from the plugin

**Comment by Meiby23** [comment]
Same for me

**Comment by Ilwyd** [comment]
I think this may be an issue with the Universalis API itself, not the plugin.

**Comment by Ilwyd** [comment]
From the Universalis Discord:

> I should've notified earlier, but better late than never — to help me mitigate the API load issues, I've temporarily enabled a global concurrent connection limit of ~12k connections. Connections over this limit globally will result in 429s. Having this limit (again, temporarily) in place prevents the gateway servers from going OOM while I attempt to debug the issue.
> 
> Once I've mitigated the underlying issue, I'll raise that limit gradually before removing it altogether

**Comment by Strider1321** [comment]
Ah, it must just be bad luck on my end of being on the API limit. Thanks for letting me know. 
I wasn't quite sure if it was the plugin or Uni so I'd figure I would create a ticket to narrow it down.
Gonna go ahead and close this then.
