### ISSUE TITLE
Failed to retrieve data from Universalis for itemId 4551, scope "Chaos".

### ISSUE THREAD

**Issue by akhos09** [Kouzukii/ffxiv-priceinsight#41]
[PriceInsight] Failed to retrieve data from Universalis for itemId 4551, scope "Chaos".
System.Net.Http.HttpRequestException: Invalid status code InternalServerError
at PriceInsight.UniversalisClient.GetMarketBoardData(String scope, UInt32 homeWorldId, UInt64 itemId) in /work/repo/UniversalisClient.cs:line 54

I just installed the plugin and everything. When I try to get the price info from Universalis db I get this error constantly.

**Comment by Ephirion** [comment]
You're not the only one. That's what I'm getting on top of the same error that you have. Initially, I've blamed my crap mobile internet, but apparently it's not an issue.

[PriceInsight] Failed to retrieve data from Universalis for itemId 5827, scope "Chaos".
System.Net.Http.HttpRequestException: Invalid status code TooManyRequests
 at PriceInsight.UniversalisClient.GetMarketBoardData(String scope, UInt32 homeWorldId, UInt64 itemId) in /work/repo/UniversalisClient.cs:line 54

**Comment by Ilwyd** [comment]
This is an issue with the Universalis API. From their discord:

> I should've notified earlier, but better late than never — to help me mitigate the API load issues, I've temporarily enabled a global concurrent connection limit of ~12k connections. Connections over this limit globally will result in 429s. Having this limit (again, temporarily) in place prevents the gateway servers from going OOM while I attempt to debug the issue.
> 
> Once I've mitigated the underlying issue, I'll raise that limit gradually before removing it altogether

**Comment by akhos09** [comment]
> This is an issue with the Universalis API. From their discord:
> 
> > I should've notified earlier, but better late than never — to help me mitigate the API load issues, I've temporarily enabled a global concurrent connection limit of ~12k connections. Connections over this limit globally will result in 429s. Having this limit (again, temporarily) in place prevents the gateway servers from going OOM while I attempt to debug the issue.
> > Once I've mitigated the underlying issue, I'll raise that limit gradually before removing it altogether

ty guys, today I also had the error and the website its also not working, I hope they fixed this as fast as posible
