### ISSUE TITLE
Mitigating the API load issue Universalis currently faces

### ISSUE THREAD

**Issue by ATroschke** [Kouzukii/ffxiv-priceinsight#42]
Hey, I've just noticed Universalis faces some heavy API loads, maybe we can check how plugins can help mitigating this?

A thing this plugin could implement (I've noticed you do have a cache for prices) is to just add all items to the request-queue that are in your inventory, so not every item you are hovering is a seperate request.

This could reduce server load and make the plugin overall more useable by making it less chatty.

Note I haven't checked on the exact implementation but would be willing to help/have a look.

**Comment by Kouzukii** [comment]
All items in your inventory, retainer and chocobo saddlebag are already pre-cached. Universalis is simply unresponsive to all requests at the moment.
