### ISSUE TITLE
Stack Values Incorrect

### ISSUE THREAD

**Issue by SzassT** [Kouzukii/ffxiv-priceinsight#47]
The value of a stack of items is incorrect for everything. For example, a stack of 5 Manganese Ingots valued at 1,400g each is showing a stack value of 14,000g which would be the value for 10. A stack of 2 Bipolar Nightmare Orchestrion Rolls value at 150g each are showing a stack value 3,900g, while 2 Alien Manifestation Orchestrion Rolls also valued at 150g each are showing a stack value of 4,050g. A single Lunar Adamantite Ingot valued at 258g is showing a stack value of 4,386g, Another user suggested that it may be showing the value of the largest stack on the market board, but I cannot confirm this.

![image](https://github.com/user-attachments/assets/ad41ff4b-5bb5-4a78-802c-ee6f7d97c2ed)
![image](https://github.com/user-attachments/assets/6111d4cb-4d8b-4729-b0f0-38c88ed6a066)
![image](https://github.com/user-attachments/assets/aa980a5e-5be9-4b7e-a3c0-40dba5a1ceb5)
![image](https://github.com/user-attachments/assets/9f067590-050c-4c76-ade8-77285f8dac51)

**Comment by Kouzukii** [comment]
Thanks for the report, I've released a fix.
