### ISSUE TITLE
Suggestion: Prefetch all prices

### ISSUE THREAD

**Issue by Iaotle** [Kouzukii/ffxiv-priceinsight#5]
I really don't enjoy having to hold ctrl to fetch prices on items. Consider fetching item prices in the background for inventory items?

**Comment by Kouzukii** [comment]
That could cause quite a bit of load to the universalis servers, that I'd like to avoid, me being unaffiliated with them and all. 

What you can do is simply quickly drag your mouse across all the items you're interested in, and after that when you hover over them, they'll have the price cached.

**Comment by Iaotle** [comment]
Alright, but could you maybe add a feature to click a button combo to fetch all current inventory prices? Dragging my mouse around 140 inventory slots takes a while and doesn't feel good.

I don't think 140 requests max is that big of a deal, especially since you're not doing them back-to-back. You can batch requests for the Universalis API so I believe they account for this.
