### ISSUE TITLE
Price display cut off

### ISSUE THREAD

**Issue by DenL** [Kouzukii/ffxiv-priceinsight#7]
For long tooltips that rests on bottom of screen, the price display is cut off like thus:
![image](https://user-images.githubusercontent.com/5632219/163724323-4083f168-b221-41db-9587-f160fa212606.png)

**Comment by Kouzukii** [comment]
Hm, I'm not sure how this could be solved. 
I was experimenting with placing the price on the item description itself. But there's so many different formats of item descriptions it would take quite a lot of effort to set that up.

**Comment by Kouzukii** [comment]
I guess for a quickfix I could move the item description window up if it cuts past the bottom of the screen.

**Comment by filliph** [comment]
@Kouzukii could you please circle back to this? AllaganTools doesn't cause this issue because it adds its item information in the description area.

See screenshot:

![image](https://user-images.githubusercontent.com/9424286/187421823-04a5b7ae-18df-44f3-a29d-4e7c236e1f63.png)

**Comment by Kouzukii** [comment]
Should be fixed now
