### ISSUE TITLE
[Bug] Menu constantly flickering on Supply Missions

### ISSUE THREAD

**Issue by Rueby** [Kouzukii/ffxiv-priceinsight#9]
I was checking the price on supply mission items. Then the black box that pops whenever you press ctrl to fetch the updates keeps flickering as if ctrl is being constantly held down. This behavior doesn't happen in Inventory/Crafting list. (I'm not sure where else I can check for it.)

Timers > Next Mission Allowance > Hover over anything

**Comment by Kouzukii** [comment]
Should be okay now that i'm not using the black box to display prices anymore
